### ISSUE TITLE
Would you please be so kind and stop trolling around on GitHub?

### ISSUE THREAD

**Issue by Joachim26** [Frosty54/Fire-NN#2]
Would you please be so kind and stop trolling around on GitHub? As I already said: Go playing elsewhere, e.g. on TikTok, it's much easier to use than GitHub, which is far to complicated for people like you. 😔

**Comment by Joachim26** [comment]
Stop trolling my friend!

**Comment by Frosty54** [comment]
You also should stop trolling. Please don't write here anything. You also should go playing everywhere. I don't put any claims on what and when to do. Please don't pester me and don't create unnecessary issues and commits in my repo, otherwise you'll get banned
